-- Update sales table for self-service functionality

-- 1. Add new columns for customer and order details
ALTER TABLE public.sales ADD COLUMN IF NOT EXISTS order_type character varying CHECK (order_type IN ('pos', 'local', 'delivery'));
ALTER TABLE public.sales ADD COLUMN IF NOT EXISTS customer_name character varying;
ALTER TABLE public.sales ADD COLUMN IF NOT EXISTS customer_phone character varying;
ALTER TABLE public.sales ADD COLUMN IF NOT EXISTS delivery_address text;
ALTER TABLE public.sales ADD COLUMN IF NOT EXISTS delivery_notes text;

-- Set default order_type for existing records to 'pos'
UPDATE public.sales SET order_type = 'pos' WHERE order_type IS NULL;
ALTER TABLE public.sales ALTER COLUMN order_type SET DEFAULT 'pos';

-- 2. Update the status check constraint to include 'pending_approval' and 'rejected'
-- First, we need to drop the existing constraint. The constraint name is generated by supabase, 
-- but usually follows the pattern "table_column_check". Let's drop and recreate.

-- Drop existing check constraint on status
ALTER TABLE public.sales DROP CONSTRAINT IF EXISTS sales_status_check;

-- Recreate constraint with new statuses
ALTER TABLE public.sales ADD CONSTRAINT sales_status_check 
  CHECK (status IN ('draft', 'pending_approval', 'preparing', 'ready', 'delivered', 'paid', 'voided', 'refunded', 'rejected'));

-- 3. Allow anonymous users to insert into sales and sale_items (for public storefront)
-- Drop existing policies if they exist to recreate them cleanly
DROP POLICY IF EXISTS "Allow anonymous inserts to sales" ON public.sales;
DROP POLICY IF EXISTS "Allow anonymous inserts to sale_items" ON public.sale_items;

-- Create policy to allow anonymous inserts to sales
CREATE POLICY "Allow anonymous inserts to sales" ON public.sales
  FOR INSERT TO public
  WITH CHECK (status = 'pending_approval' OR status = 'draft');

-- Create policy to allow anonymous inserts to sale_items
CREATE POLICY "Allow anonymous inserts to sale_items" ON public.sale_items
  FOR INSERT TO public
  WITH CHECK (true);
