-- Agregar número de pedido y descripción/observaciones en ventas

ALTER TABLE sales
  ADD COLUMN IF NOT EXISTS order_number BIGINT GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE sales
  ADD COLUMN IF NOT EXISTS description TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS idx_sales_order_number ON sales(order_number);

